apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: flexdeck

resources:
  - namespace.yaml
  - serviceaccount.yaml
  - public-serviceaccount.yaml
  - secret.sops.yaml
  - redis.yaml
  - workspace-pvc.yaml
  - deployment.yaml
  - public-deployment.yaml
  - service.yaml
  - public-service.yaml
  - ingress.yaml

labels:
  - pairs:
      app.kubernetes.io/name: flexdeck
      app.kubernetes.io/part-of: flexdeck
      app.kubernetes.io/managed-by: flux
    includeSelectors: false

images:
  - name: registry.harbor.lan/library/flexdeck
    newTag: latest
