apiVersion: v1
kind: Service
metadata:
  name: flexdeck-public
  namespace: flexdeck
  labels:
    app.kubernetes.io/name: flexdeck
    app.kubernetes.io/component: public-api
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 80
      targetPort: http
      protocol: TCP
  selector:
    app.kubernetes.io/name: flexdeck
    app.kubernetes.io/component: public-api
