apiVersion: v1
kind: Secret
metadata:
    name: flexdeck-secrets
    namespace: flexdeck
    labels:
        app.kubernetes.io/name: flexdeck
type: Opaque
stringData:
    gitlab-token: ENC[AES256_GCM,data:SuGf0ASKCbJ5ENGpLchGkeGkttqVovJxZ+ispI+MD+XWGw/iXULGjlXIf5bbj7NQeeek,iv:kgUHNiHPjM3b0d6h5l+0d7Z9KluZwBAbn993qJQSMM0=,tag:bRbOjtI0HMgLxsteD66iHQ==,type:str]
    litellm-api-key: ENC[AES256_GCM,data:Nz3UTRHAPRUTLCxuheIH+Q==,iv:vGKetTkgyUaFwVBN6Hvd3bJmyn7l2Yod4d1u24/D028=,tag:fwTgcOaloTFuqFp6v1f+6g==,type:str]
    langfuse-public-key: ENC[AES256_GCM,data:S5SjxkMiIimFp5Dt/9hxHhlDoqB3itA=,iv:e5kwPBsg5Htfaa1a8hZFknmeQPZQn8mOeeqrcYWvtNk=,tag:p35UoD0ZZTp6yTb8AqjCnA==,type:str]
    langfuse-secret-key: ENC[AES256_GCM,data:jKvprKOJC+zEBwrACKhldxtLOz2AV94=,iv:VvP2tW5itlmSE8Gca4wikHZMczhXLTGKPlU5r1FGlbE=,tag:jC1RFCXlRxagB54o+EYv3A==,type:str]
    grafana-token: ENC[AES256_GCM,data:8jhoZFpSUxhLg9EhskhCEtx8woSzUXTyQ31WlOtJznkJE69iMyEq5fc2UC9CWg==,iv:4xEUAIm4l4dAg9nJV+U30tafC3Vup/JZWiMFSUc7WsQ=,tag:k1+gTjODTbc9pxUwTrD8eQ==,type:str]
    hud-push-token: ENC[AES256_GCM,data:vVWZo8GsJdiDXmj7Mpc1NqiAWD+pRWUw4MdC1Vnr6m8jvAOcd96v+kvN4/pjaRq12ZC6E7zTYQJy+9kVI9dENg==,iv:FOUyqVxilkdrdyAgVxa2QJ4ZLHEHJiWGaQW+e+6R5c0=,tag:4tXPLQKQXZXJ6Neg1xyN4w==,type:str]
sops:
    age:
        - recipient: age1d8mxyz340rdexgn068097s0le3tmf3898xd5a4qpqng4zdtg8sgswnx9r9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAra3AvRWRTVFRSNUpZazNR
            MVpERm5UUURicVQyU0F1WGUwNE1LbmtJazNBCmNFa2ppdmdxRFhyclRiODk0TGZX
            Vll4Ny8yNmJiNmVjU1BwVU90OC95a3cKLS0tIExvTlhIN0x3cytIMW9XaEhYQU9j
            YVNSY01SajB2UE4zQkErRERPbGQwSVkK7NrV6pB80u13oiGOE7IK0+NLDdyLF2a5
            LyXGdiJc0u2odP82+Bna+yCk5VVmqp/BjUDsZD53w/hw1fD3/pqaYQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-27T20:01:05Z"
    mac: ENC[AES256_GCM,data:2XFqi9SZz0HDNO5VIgDU//rvB7Y3ajhx3tLGVDUjuRYsvR8NBibhRpbh6B89A/IngG8Jwrv5e2VJzTWkRCwHXDL00YKySmQ0OQdXI0+nxf2vdBnRjI5pT8OzZ/6rqup1Cd1Z1Yl0sQWvWf+em2/Q0+xh0mlo3d+dIG/lra2tGds=,iv:amlQHbaobu5GZxgbAmM9VsWLRTnKt/So6eczZ8OHdRs=,tag:mBQSG886HC21c12jgnQjxA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
