apiVersion: v1
kind: Secret
metadata:
    name: flexdeck-secrets
    namespace: flexdeck
    labels:
        app.kubernetes.io/name: flexdeck
type: Opaque
stringData:
    gitlab-token: ENC[AES256_GCM,data:TdglcoYcclvtByN+y4iaKaRAeaPobXzRoxaDURKQz68HzEDScQegVc/fH2t4BE8bsXdF,iv:2lUfLwjX3X/zWG7jsMyDJnOmtTUjwJX92krGCKTTgaA=,tag:wWkANx/mD/50/+NSR+lNfQ==,type:str]
    litellm-api-key: ""
sops:
    age:
        - recipient: age1d8mxyz340rdexgn068097s0le3tmf3898xd5a4qpqng4zdtg8sgswnx9r9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5eldVR29JdWU4M0xDK09J
            V3NEYlVJMElLb1grRStid1ZPSHo3WEhOL2g4ClVXcWlMZFlEaUdsdVkwdU5OZlU3
            OVE4TDBLNFlNbmJJdzNuak9ycnZsSFEKLS0tIEtLMXRISzlwNXFYcjEvL3NhRnZo
            UTVXdDBXRmtTM3dTMzJ3dElaMVhjelUKpjF5xIC+/4XgvgygJkIzseQPn1cnQJLg
            X0CMcQSauuqfee/OCwn07Wng76FCjGokUqK2nRWZx+fQIMvFAl0UDA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-27T19:13:12Z"
    mac: ENC[AES256_GCM,data:MQluZNc/j0Fko2Cy9VnRvOKQtgVKPrSyopXFH8BpUreSUaicO+lCFcyXxMmvurdeo2pwNOujpnU6RZDIEn0wUiKJVknatk7wEKLk3F5L2JGYmG5ZokuAWI8Ad7SaNW7/ehrcnBRdPRi6eo+13pCQXqnoVs4fB6t+Qs7+IhBgPgg=,iv:BEPDLzoMycns0KRIHvdDwJI+ELh1WKQB9QqZ46ZqRqo=,tag:e5Or3BYxsDKS8wa7gL31FA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
