apiVersion: v1
kind: Secret
metadata:
    name: flexdeck-secrets
    namespace: flexdeck
    labels:
        app.kubernetes.io/name: flexdeck
type: Opaque
stringData:
    gitlab-token: ENC[AES256_GCM,data:RfYPxQY/ig9EgSyWeP/VFeRmr4tjqQAtdVJJHsuQ3zFABto0ga4RDDdgcM/jWmkWC7Cx,iv:5yOPRiUTdd6RjT/BcAUc4LAULNzPyyz6mpnVRQ1gXsg=,tag:PLrgg5IqVyIfAqI/7g3qxQ==,type:str]
    litellm-api-key: ENC[AES256_GCM,data:CQR1cmGK5DCvvZsEwFcwJg==,iv:5H66YaxerOG3gJVH1hpaXzOYAByrBCWVFq56pV1Bm1w=,tag:O7b33wEEjmBrrFf1RK8Ayw==,type:str]
    langfuse-public-key: ENC[AES256_GCM,data:8trfOTRAOalx5TWILl450nDkB2+pIw8=,iv:raViNuurWB3lUgCpWesBXQ0mU94JJpErH9K6Nq3oeDo=,tag://jfzUiKxhPtevilNYy70g==,type:str]
    langfuse-secret-key: ENC[AES256_GCM,data:NDNHmxGQhjjBQqv0bgsZiOrVGJ062KM=,iv:EKXeGcsV0WAaea8fML/9+kYjebWk56uV4tmhR2CcDBs=,tag:NvgfGlWHpDho2tjS1ws4XQ==,type:str]
    hud-push-token: ENC[AES256_GCM,data:j2F0vPXmvsEAq8vR1YMXyCxPofBxxpPiTX7cI898liwtMEKwb+Me4/hYKlLZEgenkvHtYyi7nmcDc70NfrysYw==,iv:8G360pGWnCzRQSQAdWcwSmJ7mmn49AfSXhFDaECUMOA=,tag:VWeUyXSKEWGD0nmF2hV4lA==,type:str]
sops:
    age:
        - recipient: age1d8mxyz340rdexgn068097s0le3tmf3898xd5a4qpqng4zdtg8sgswnx9r9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOdXZqandzTHRMN1JabG1H
            REN6K1hUaHhyRmw4QzlUN0xDaWtzSVVjUm1zCnNaUXJOVUpCeXhKakxkSFpUM2pT
            bWF1OTJSKzlhd0p3eGZMbk5rMFBsQnMKLS0tIEREcFZMMzlUd1hNb3NrZVlVR3RG
            NjFJeXJ2VHprK1g1ZStxNTN1c1FjUk0K0sOA0D614tAUdkEFK4gg9yk/invp3VaU
            3FG3VWQR61/X/+l1FfDl3w9G5Yo78Wwow+uw7t3XY3gVpIVpBYKaeQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-16T20:28:44Z"
    mac: ENC[AES256_GCM,data:wdNIa/3yHnFB3AuaHmkjS4dsH5Y3tdh7lHFx3PjYmmuvJq9ilFxhND72WKvG/jnEx2MGw8j6Icaf3DNHFPMSSh+eGuhC8Efxk8ug1v4HUVFxb6X84+ZcXMhzOVHF55SlGnNvUXDTvH+rmVqzCeG503J8SMK/wAdOy/9cVfcq8iI=,iv:cKsAwR4A5lHjHbhEbX61bE1z4z6NgXY3S0lGqv5ZRIw=,tag:xVfUIhghIQZBR8epxJ3IHg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
