apiVersion: v1
kind: Service
metadata:
  name: flexdeck
  namespace: flexdeck
  labels:
    app.kubernetes.io/name: flexdeck
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 80
      targetPort: http
      protocol: TCP
  selector:
    app.kubernetes.io/name: flexdeck
